project:
  type: website
  output-dir: docs

website:
  title: "Welcome!"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Resume
        href: resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



